name: CI - Build CLI

on:
  push:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Build CLI
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: pyinstaller OCLP-CLI.spec
      - run: cd dist; zip ../OCLP-CLI.zip OCLP-CLI
      - name: Upload Binary to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: OCLP-CLI
          path: OCLP-CLI.zip
      - name: Upload to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@e74ff71f7d8a4c4745b560a485cc5fdb9b5b999d
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: OCLP-CLI.zip
          tag: ${{ github.ref }}
          file_glob: true
